"""
Intelli Depot — Perimeter Monitoring
Feature: DEPOT-V7

Zone-based perimeter breach detection, unauthorized-access alerts, and
incident tracking. Integrates with camera feeds (DEPOT-V1).

Dependency note: AUTH-6.2 (RBAC) is active.
Permission checks now use the shared RBAC dependency layer.

Detection note: Real motion/object detection triggering requires DEPOT-V2.
This module exposes a `POST /breaches` endpoint that accepts breach events
(generated by the detection pipeline or a hardware sensor) and a
`POST /breaches/simulate` helper for testing without live camera feeds.
"""
import uuid
import logging
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.database import BaseModel as DBBaseModel, get_db
from app.core.auth.dependencies import get_current_user, require_permission
from app.core.redis_client import get_redis
from app.core.notifications.service_compat import NotificationService
from app.shared.models.user import User
import redis.asyncio as aioredis

logger = logging.getLogger("intelli.depot.perimeter")

router = APIRouter(prefix="/depot/vision/perimeter", tags=["Depot - Perimeter"])




# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ZoneType(str, Enum):
    RESTRICTED = "restricted"       # no-entry at all times
    CONTROLLED = "controlled"       # entry allowed with authorisation
    HAZARDOUS = "hazardous"         # PPE or safety clearance required
    LOADING = "loading"             # dock / vehicle zone
    GENERAL = "general"             # monitored but unrestricted


class BreachType(str, Enum):
    UNAUTHORIZED_ENTRY = "unauthorized_entry"
    LOITERING = "loitering"
    FORCED_ENTRY = "forced_entry"
    AFTER_HOURS = "after_hours"
    OBJECT_LEFT = "object_left"
    UNKNOWN = "unknown"


class AlertSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# ---------------------------------------------------------------------------
# Database Models
# ---------------------------------------------------------------------------

class PerimeterZone(DBBaseModel):
    """A monitored perimeter zone associated with one or more cameras."""
    __tablename__ = "depot_perimeter_zones"

    name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    zone_type = Column(String, default=ZoneType.RESTRICTED)
    camera_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    # polygon stored as JSON string: "[[x1,y1],[x2,y2],...]" (normalised 0-1)
    polygon_points = Column(Text, nullable=True)
    alert_on_entry = Column(Boolean, default=True)
    alert_severity = Column(String, default=AlertSeverity.HIGH)
    night_vision_enabled = Column(Boolean, default=False)
    night_vision_mode = Column(String, default="auto")  # auto, ir, thermal, off
    active_hours_start = Column(String, nullable=True)  # e.g. "06:00"
    active_hours_end = Column(String, nullable=True)    # e.g. "22:00"
    is_active = Column(Boolean, default=True)
    created_by = Column(String, nullable=True)


class PerimeterBreach(DBBaseModel):
    """An immutable breach event record."""
    __tablename__ = "depot_perimeter_breaches"

    zone_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    camera_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    breach_type = Column(String, default=BreachType.UNAUTHORIZED_ENTRY)
    severity = Column(String, default=AlertSeverity.HIGH)
    confidence = Column(Float, nullable=True)
    snapshot_ref = Column(String, nullable=True)  # path/URL to frame snapshot
    alert_sent = Column(Boolean, default=False)
    notes = Column(Text, nullable=True)
    detected_at = Column(DateTime(timezone=True), nullable=False)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    resolved_by = Column(String, nullable=True)
    resolution_notes = Column(Text, nullable=True)


# ---------------------------------------------------------------------------
# Pydantic Schemas
# ---------------------------------------------------------------------------

class PerimeterZoneCreate(BaseModel):
    name: str = Field(..., json_schema_extra={"example": "Server Room Entrance"})
    description: Optional[str] = None
    zone_type: ZoneType = ZoneType.RESTRICTED
    camera_id: Optional[uuid.UUID] = None
    polygon_points: Optional[str] = Field(
        None,
        example="[[0.1,0.1],[0.9,0.1],[0.9,0.9],[0.1,0.9]]",
        description="JSON array of [x,y] pairs, coordinates normalised 0-1",
    )
    alert_on_entry: bool = True
    alert_severity: AlertSeverity = AlertSeverity.HIGH


class PerimeterZoneResponse(BaseModel):
    id: uuid.UUID
    name: str
    description: Optional[str]
    zone_type: str
    camera_id: Optional[uuid.UUID]
    polygon_points: Optional[str]
    alert_on_entry: bool
    alert_severity: str
    is_active: bool
    created_by: Optional[str]
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class BreachCreate(BaseModel):
    zone_id: uuid.UUID
    camera_id: Optional[uuid.UUID] = None
    breach_type: BreachType = BreachType.UNAUTHORIZED_ENTRY
    confidence: Optional[float] = Field(None, ge=0.0, le=1.0)
    snapshot_ref: Optional[str] = None
    notes: Optional[str] = None
    detected_at: Optional[datetime] = None


class BreachResponse(BaseModel):
    id: uuid.UUID
    zone_id: uuid.UUID
    camera_id: Optional[uuid.UUID]
    breach_type: str
    severity: str
    confidence: Optional[float]
    snapshot_ref: Optional[str]
    alert_sent: bool
    notes: Optional[str]
    detected_at: datetime
    resolved_at: Optional[datetime]
    resolved_by: Optional[str]
    resolution_notes: Optional[str]
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class BreachResolve(BaseModel):
    resolution_notes: Optional[str] = Field(None, json_schema_extra={"example": "Authorised maintenance team entry confirmed"})


class SimulateBreachRequest(BaseModel):
    zone_id: uuid.UUID
    breach_type: BreachType = BreachType.UNAUTHORIZED_ENTRY
    confidence: float = Field(0.87, ge=0.0, le=1.0)
    notes: Optional[str] = Field("Simulated breach for testing", json_schema_extra={"example": "Simulated breach for testing"})


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _severity_for_zone(zone: PerimeterZone) -> str:
    """Derive breach severity from zone configuration."""
    return zone.alert_severity


# ---------------------------------------------------------------------------
# Zone Endpoints
# ---------------------------------------------------------------------------

@router.post("/zones", response_model=PerimeterZoneResponse, status_code=201)
async def create_zone(
    payload: PerimeterZoneCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Register a new perimeter zone."""
    zone = PerimeterZone(**payload.model_dump(), created_by=str(current_user.id))
    db.add(zone)
    await db.commit()
    await db.refresh(zone)
    logger.info(f"Perimeter zone created: {zone.name} ({zone.zone_type})")
    return zone


@router.get("/zones", response_model=list[PerimeterZoneResponse])
async def list_zones(
    zone_type: Optional[ZoneType] = None,
    camera_id: Optional[uuid.UUID] = None,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List active perimeter zones."""
    query = select(PerimeterZone).where(PerimeterZone.is_active == True)
    if zone_type:
        query = query.where(PerimeterZone.zone_type == zone_type)
    if camera_id:
        query = query.where(PerimeterZone.camera_id == camera_id)
    result = await db.execute(query)
    return result.scalars().all()


@router.get("/zones/{zone_id}", response_model=PerimeterZoneResponse)
async def get_zone(
    zone_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Get a specific perimeter zone."""
    zone = await db.get(PerimeterZone, zone_id)
    if not zone or not zone.is_active:
        raise HTTPException(status_code=404, detail="Perimeter zone not found")
    return zone


@router.patch("/zones/{zone_id}/deactivate", response_model=PerimeterZoneResponse)
async def deactivate_zone(
    zone_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Deactivate a perimeter zone (stops alerting)."""
    zone = await db.get(PerimeterZone, zone_id)
    if not zone:
        raise HTTPException(status_code=404, detail="Perimeter zone not found")
    zone.is_active = False
    await db.commit()
    await db.refresh(zone)
    logger.info(f"Perimeter zone deactivated: {zone.name}")
    return zone


# ---------------------------------------------------------------------------
# Breach Endpoints
# ---------------------------------------------------------------------------

@router.post("/breaches", response_model=BreachResponse, status_code=201)
async def log_breach(
    payload: BreachCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Log a perimeter breach event.
    Called by the detection pipeline (DEPOT-V2) or hardware sensors.
    """
    zone = await db.get(PerimeterZone, payload.zone_id)
    if not zone:
        raise HTTPException(status_code=404, detail="Perimeter zone not found")

    breach = PerimeterBreach(
        zone_id=payload.zone_id,
        camera_id=payload.camera_id or zone.camera_id,
        breach_type=payload.breach_type,
        severity=_severity_for_zone(zone),
        confidence=payload.confidence,
        snapshot_ref=payload.snapshot_ref,
        notes=payload.notes,
        detected_at=payload.detected_at or datetime.now(timezone.utc),
        alert_sent=zone.alert_on_entry,
    )
    db.add(breach)
    await db.commit()
    await db.refresh(breach)
    logger.warning(
        f"BREACH [{breach.severity.upper()}] zone={zone.name} "
        f"type={breach.breach_type} conf={breach.confidence}"
    )
    return breach


@router.post("/breaches/simulate", response_model=BreachResponse, status_code=201)
async def simulate_breach(
    payload: SimulateBreachRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Inject a synthetic breach event for testing and demo purposes."""
    zone = await db.get(PerimeterZone, payload.zone_id)
    if not zone:
        raise HTTPException(status_code=404, detail="Perimeter zone not found")

    breach = PerimeterBreach(
        zone_id=payload.zone_id,
        camera_id=zone.camera_id,
        breach_type=payload.breach_type,
        severity=_severity_for_zone(zone),
        confidence=payload.confidence,
        snapshot_ref="simulated://frame-0",
        notes=payload.notes,
        detected_at=datetime.now(timezone.utc),
        alert_sent=False,
    )
    db.add(breach)
    await db.commit()
    await db.refresh(breach)
    logger.info(f"Simulated breach logged for zone {zone.name}")
    return breach


@router.get("/breaches", response_model=list[BreachResponse])
async def list_breaches(
    zone_id: Optional[uuid.UUID] = None,
    resolved: Optional[bool] = None,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List breach events with optional filters."""
    query = select(PerimeterBreach)
    if zone_id:
        query = query.where(PerimeterBreach.zone_id == zone_id)
    if resolved is True:
        query = query.where(PerimeterBreach.resolved_at.isnot(None))
    elif resolved is False:
        query = query.where(PerimeterBreach.resolved_at.is_(None))
    result = await db.execute(query.order_by(PerimeterBreach.detected_at.desc()))
    return result.scalars().all()


@router.get("/breaches/active", response_model=list[BreachResponse])
async def active_breaches(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Return all unresolved breach events."""
    result = await db.execute(
        select(PerimeterBreach)
        .where(PerimeterBreach.resolved_at.is_(None))
        .order_by(PerimeterBreach.detected_at.desc())
    )
    return result.scalars().all()


@router.patch("/breaches/{breach_id}/resolve", response_model=BreachResponse)
async def resolve_breach(
    breach_id: uuid.UUID,
    payload: BreachResolve,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Mark a breach as resolved."""
    breach = await db.get(PerimeterBreach, breach_id)
    if not breach:
        raise HTTPException(status_code=404, detail="Breach not found")
    if breach.resolved_at:
        raise HTTPException(status_code=409, detail="Breach already resolved")
    breach.resolved_at = datetime.now(timezone.utc)
    breach.resolved_by = str(current_user.id)
    breach.resolution_notes = payload.resolution_notes
    await db.commit()
    await db.refresh(breach)
    logger.info(f"Breach {breach_id} resolved by {str(current_user.id)}")
    return breach


# ---------------------------------------------------------------------------
# Night Vision Configuration
# ---------------------------------------------------------------------------

class NightVisionConfig(BaseModel):
    night_vision_enabled: bool = True
    night_vision_mode: str = Field("auto", description="auto, ir, thermal, off")
    active_hours_start: Optional[str] = Field(None, json_schema_extra={"example": "06:00"})
    active_hours_end: Optional[str] = Field(None, json_schema_extra={"example": "22:00"})


@router.patch("/zones/{zone_id}/night-vision", response_model=PerimeterZoneResponse)
async def configure_night_vision(
    zone_id: uuid.UUID,
    payload: NightVisionConfig,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Configure night vision mode for a perimeter zone.
    Modes: auto (switch IR on by light level), ir (always infrared),
    thermal (thermal imaging), off (disabled).
    Active hours define when standard vision is used vs. night vision.
    """
    zone = await db.get(PerimeterZone, zone_id)
    if not zone or not zone.is_active:
        raise HTTPException(status_code=404, detail="Zone not found")
    zone.night_vision_enabled = payload.night_vision_enabled
    zone.night_vision_mode = payload.night_vision_mode
    zone.active_hours_start = payload.active_hours_start
    zone.active_hours_end = payload.active_hours_end
    await db.commit()
    await db.refresh(zone)
    logger.info(f"Night vision configured for zone {zone.name}: mode={payload.night_vision_mode}")
    return zone


# ---------------------------------------------------------------------------
# Security Breach Agent — autonomous breach detection & dispatch
# ---------------------------------------------------------------------------

class BreachAgentRequest(BaseModel):
    """Trigger the Security Breach Agent to scan all active zones."""
    camera_id: Optional[uuid.UUID] = None
    simulate_breach_count: int = Field(0, ge=0, le=10, description="Number of synthetic breaches to generate for testing")


class BreachAgentResult(BaseModel):
    zones_scanned: int
    breaches_detected: int
    alerts_dispatched: int
    breaches: list[BreachResponse]


@router.post("/agent/scan", response_model=BreachAgentResult, status_code=200)
async def run_security_breach_agent(
    payload: BreachAgentRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    redis: aioredis.Redis = Depends(get_redis),
):
    """
    Security Breach Agent: autonomously scans all active perimeter zones,
    detects motion/intrusion events (simulated until real CV pipeline is wired),
    logs breach records, and dispatches alerts to the Notification Hub.

    Supports night vision zones — adjusts detection confidence for IR/thermal modes.
    """
    import random

    # Get all active zones, optionally filtered by camera
    query = select(PerimeterZone).where(PerimeterZone.is_active == True)
    if payload.camera_id:
        query = query.where(PerimeterZone.camera_id == payload.camera_id)
    result = await db.execute(query)
    zones = list(result.scalars().all())

    if not zones:
        raise HTTPException(status_code=404, detail="No active perimeter zones found")

    breaches_created: list[PerimeterBreach] = []
    alerts_dispatched = 0

    for zone in zones:
        # Simulate breach detection — replace with real motion detection pipeline
        # Night vision zones get slightly lower confidence in thermal/IR mode
        base_confidence = 0.92
        if zone.night_vision_enabled and zone.night_vision_mode in ("ir", "thermal"):
            base_confidence = 0.85

        # Determine if a breach is detected (simulated)
        breach_detected = (payload.simulate_breach_count > len(breaches_created))

        if not breach_detected:
            continue

        # Determine breach type based on zone type and time
        breach_type = BreachType.UNAUTHORIZED_ENTRY
        if zone.zone_type == ZoneType.RESTRICTED:
            breach_type = BreachType.UNAUTHORIZED_ENTRY
        elif zone.zone_type == ZoneType.HAZARDOUS:
            breach_type = BreachType.FORCED_ENTRY

        # Check if after hours
        current_hour = datetime.now(timezone.utc).hour
        if zone.active_hours_end:
            try:
                end_hour = int(zone.active_hours_end.split(":")[0])
                if current_hour >= end_hour or current_hour < 6:
                    breach_type = BreachType.AFTER_HOURS
            except ValueError:
                pass

        confidence = round(random.uniform(base_confidence - 0.05, base_confidence + 0.05), 4)
        severity = _severity_for_zone(zone)

        breach = PerimeterBreach(
            zone_id=zone.id,
            camera_id=zone.camera_id,
            breach_type=breach_type,
            severity=severity,
            confidence=confidence,
            snapshot_ref=f"agent://scan-{datetime.now(timezone.utc).isoformat()}",
            notes=f"Detected by Security Breach Agent. Night vision: {zone.night_vision_mode if zone.night_vision_enabled else 'off'}",
            detected_at=datetime.now(timezone.utc),
            alert_sent=True,
        )
        db.add(breach)
        breaches_created.append(breach)

        # Dispatch to Notification Hub
        try:
            priority_map = {"low": "LOW", "medium": "NORMAL", "high": "HIGH", "critical": "CRITICAL"}
            await NotificationService.send_alert(
                db=db,
                redis=redis,
                user_id=current_user.id,
                event_type="depot.perimeter.breach",
                title=f"Security Breach — {zone.name}",
                message=f"{breach_type.value.replace('_', ' ').title()} detected in {zone.name} (confidence: {confidence:.0%})",
                priority=priority_map.get(severity, "HIGH"),
                payload={
                    "zone_name": zone.name,
                    "zone_type": zone.zone_type,
                    "breach_type": breach_type,
                    "confidence": confidence,
                    "night_vision": zone.night_vision_enabled,
                },
                channel="in_app",
            )
            alerts_dispatched += 1
        except Exception as e:
            logger.warning(f"Failed to dispatch breach alert for zone {zone.name}: {e}")

    await db.commit()
    for b in breaches_created:
        await db.refresh(b)

    logger.info(
        f"Security Breach Agent: scanned {len(zones)} zones, "
        f"detected {len(breaches_created)} breaches, dispatched {alerts_dispatched} alerts"
    )

    return BreachAgentResult(
        zones_scanned=len(zones),
        breaches_detected=len(breaches_created),
        alerts_dispatched=alerts_dispatched,
        breaches=[BreachResponse.model_validate(b) for b in breaches_created],
    )
